### ISSUE TITLE
[Suggestion] Different background color for html strings

### ISSUE THREAD

**Issue by mariusGundersen** [pushqrdx/vscode-inline-html#1] opened 2018-10-25 08:42 UTC
I have a small suggestion for a feature: show the syntax highlighted html with a slightly different background color, to make it clearer where the html string starts and stops. Not sure if this is possible though?

**Comment by pushqrdx** [comment] 2018-11-09 04:51
@mariusGundersen sorry i didn't answer this more early. So the syntax colors for the html function is governed by your color scheme the extension treats html as a normal typescript/javascript function then anything between the tilde ` as html. the tilde symbol itself is treated as a string.

So altering how those are treated would result in a maybe unpleasant experience for users who expect things to behave normally.

**Comment by pushqrdx** [comment] 2018-12-19 02:59
Closing this as it works are intended (by design).

**Comment by pushqrdx** [comment] 2018-12-22 05:54
Actually, I am reopening this as i can definitely see what you're describing now.

**Comment by pushqrdx** [comment] 2019-01-08 18:07
closing this as issue seems to be fixed, requester confirmation wasn't received. Feel free to reopen.

**Closed by pushqrdx** 2019-01-08 18:07 UTC
Labels: bug, help wanted
