### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 007tisumon** [pushqrdx/vscode-inline-html#22] opened 2021-10-28 13:07 UTC
- Issue Type: `Performance`
- Extension Name: `inline-html`
- Extension Version: `0.3.3`
- OS Version: `Windows_NT x64 10.0.22483`
- VS Code version: `1.61.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\tisum\AppData\Local\Temp\pushqrdx.inline-html-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by pushqrdx** [comment] 2021-11-11 19:31
@007tisumon i will try to see what's causing this, pretty sure it is either a vscode update that messed things up or another extension you have that is interactive weirdly with inline-html, can you please give it a go with only inline-html enabled?

**Comment by pushqrdx** [comment] 2022-01-21 02:37
i still can't reproduce this

**Comment by pushqrdx** [comment] 2022-01-29 18:08
closing as non-reproducible, please feel free to reopen if you still have this issue

**Closed by pushqrdx** 2022-01-29 18:08 UTC
